
USE Salutation;

/**
 * Insert russian synonyms for firstnames
 */
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Aleksander' and typ<>'=' limit 1), 'Oleksander', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Aleksandr' and typ<>'=' limit 1),'Aliaksandr', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Aleksandr' and typ<>'=' limit 1),'Oleksandr', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Aleksandra' and typ<>'=' limit 1),'Aliaksandra', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Aleksandra' and typ<>'=' limit 1),'Oleksandra', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Aleksey' and typ<>'=' limit 1),'Aliaksei', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Aleksey' and typ<>'=' limit 1),'Aliaksey', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Aleksey' and typ<>'=' limit 1),'Oleksey', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Aleksey' and typ<>'=' limit 1),'Oleksii', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Aleksey' and typ<>'=' limit 1),'Oleksij', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Aleksey' and typ<>'=' limit 1),'Oleksiy', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Alexander' and typ<>'=' limit 1),'Olexander', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Alexandr' and typ<>'=' limit 1),'Olexandr', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Alexandra' and typ<>'=' limit 1),'Olexandra', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Alexey' and typ<>'=' limit 1),'Olexiy', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Anatoliy' and typ<>'=' limit 1),'Anatol', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Andrey' and typ<>'=' limit 1),'Andrii', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Andrey' and typ<>'=' limit 1),'Andrij', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Andrey' and typ<>'=' limit 1),'Andriy', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Artiom' and typ<>'=' limit 1),'Artsiom', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Boris' and typ<>'=' limit 1),'Barys', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Boris' and typ<>'=' limit 1),'Borys', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Dariya' and typ<>'=' limit 1),'Daryia', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Denis' and typ<>'=' limit 1),'Denys', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Diana' and typ<>'=' limit 1),'Dziana', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Diyana' and typ<>'=' limit 1),'Dziyana', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Dmitriy' and typ<>'=' limit 1),'Dmitro', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Dmitriy'),'Dmytriy', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Dmitriy' and typ<>'=' limit 1),'Dmytro', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Dmitriy' and typ<>'=' limit 1),'Dzimitry', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Dmitriy' and typ<>'=' limit 1),'Dzmitrij', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Dmitriy' and typ<>'=' limit 1),'Dzmitriy', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Dmitry' and typ<>'=' limit 1),'Dzmitry', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Dzmitri' and typ<>'=' limit 1),'Dzmitri', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Elena' and typ<>'=' limit 1),'Ellina', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Evgeniy' and typ<>'=' limit 1),'Eugeni', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Fedor' and typ<>'=' limit 1),'Fedir', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Galina' and typ<>'=' limit 1),'Galyna', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Gennadiy' and typ<>'=' limit 1),'Henadz', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Gennadiy' and typ<>'=' limit 1),'Henadzi', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Gennadiy' and typ<>'=' limit 1),'Hennadij', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Gennadiy' and typ<>'=' limit 1),'Hennadiy', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Gennadiy' and typ<>'=' limit 1),'Hennadzy', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Georgiy' and typ<>'=' limit 1),'Georgii', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Grigorij' and typ<>'=' limit 1),'Grygorij', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Grigoriy' and typ<>'=' limit 1),'Grigorii', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Grigoriy' and typ<>'=' limit 1),'Grygorii', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Grigoriy' and typ<>'=' limit 1),'Grygory', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Igor' and typ<>'=' limit 1),'Ihar', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Igor' and typ<>'=' limit 1),'Ihor', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Ilya' and typ<>'=' limit 1),'Illya', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Irina' and typ<>'=' limit 1),'Iryna', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Jevgenija' and typ<>'=' limit 1),'Jevgenija', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Jevgeniy' and typ<>'=' limit 1),'Jevgeniy', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Jevgeniy' and typ<>'=' limit 1),'Yevgen', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Juri' and typ<>'=' limit 1),'Juriy', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Katerina' and typ<>'=' limit 1),'Kateryna', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Katerina' and typ<>'=' limit 1),'Katsiaryna', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Kiril' and typ<>'=' limit 1),'Kiryl', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Kiril' and typ<>'=' limit 1),'Kiryll', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Kiril' and typ<>'=' limit 1),'Kyrylo', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Konstantin' and typ<>'=' limit 1),'Kanstantsin', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Konstantin' and typ<>'=' limit 1),'Konstantyn', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Konstantin' and typ<>'=' limit 1),'Kostiantyn', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Konstantin' and typ<>'=' limit 1),'Kostyantin', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Konstantin' and typ<>'=' limit 1),'Kostyantyn', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Kristina' and typ<>'=' limit 1),'Khrystyna', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Kristina' and typ<>'=' limit 1),'Kristsina', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Kristina' and typ<>'=' limit 1),'Krystina', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Kristina' and typ<>'=' limit 1),'Krystsina', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Kristina' and typ<>'=' limit 1),'Krystyna', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Larisa' and typ<>'=' limit 1),'Larysa', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Leonid' and typ<>'=' limit 1),'Leanid', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Lubomir' and typ<>'=' limit 1),'Lubomir', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Ludmila' and typ<>'=' limit 1),'Ludmyla', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Lyudmila' and typ<>'=' limit 1),'Lyudmyla', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Margarita' and typ<>'=' limit 1),'Marharita', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Margarita' and typ<>'=' limit 1),'Marharyta', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Margaryta' and typ<>'=' limit 1),'Margaryta', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Marina' and typ<>'=' limit 1),'Maryna', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Mariya' and typ<>'=' limit 1),'Maryia', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Mariya' and typ<>'=' limit 1),'Naryja', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Maxim' and typ<>'=' limit 1),'Maksym', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Michail' and typ<>'=' limit 1),'Michailo', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Michail' and typ<>'=' limit 1),'Michaylo', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Michail' and typ<>'=' limit 1),'Mihail', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Mikhail' and typ<>'=' limit 1),'Mikhailo', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Mikhail' and typ<>'=' limit 1),'Mikhaylo', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Mikhail' and typ<>'=' limit 1),'Mykhailo', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Mikhail' and typ<>'=' limit 1),'Mykhajlo', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Mikhail' and typ<>'=' limit 1),'Mykhaylo', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Miroslav' and typ<>'=' limit 1),'Myroslav', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Miroslava' and typ<>'=' limit 1),'Myroslava', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Nadya' and typ<>'=' limit 1),'Nadija', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Nadya' and typ<>'=' limit 1),'Nadiya', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Natalya' and typ<>'=' limit 1),'Nataliia', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Natalya' and typ<>'=' limit 1),'Natallia', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Nikolay' and typ<>'=' limit 1),'Mikalai', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Nikolay' and typ<>'=' limit 1),'Mikalaj', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Nikolay' and typ<>'=' limit 1),'Mikola', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Nikolay' and typ<>'=' limit 1),'Mykola', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Oksana' and typ<>'=' limit 1),'Aksana', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Oleg' and typ<>'=' limit 1),'Aleg', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Oleg' and typ<>'=' limit 1),'Aleh', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Oleg' and typ<>'=' limit 1),'Oleh', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Olesia' and typ<>'=' limit 1),'Alesia', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Olesja' and typ<>'=' limit 1),'Alesja', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Olessja' and typ<>'=' limit 1),'Alessja', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Olessya' and typ<>'=' limit 1),'Alessya', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Olesya' and typ<>'=' limit 1),'Alesya', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Olga' and typ<>'=' limit 1),'Olha', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Olga' and typ<>'=' limit 1),'Volha', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Roman' and typ<>'=' limit 1),'Raman', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Rostislav' and typ<>'=' limit 1),'Rostyslav', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Sergej' and typ<>'=' limit 1),'Serhij', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Sergey' and typ<>'=' limit 1),'Sergii', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Sergey' and typ<>'=' limit 1),'Sergij', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Sergey' and typ<>'=' limit 1),'Sergiy', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Sergey' and typ<>'=' limit 1),'Serhei', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Sergey' and typ<>'=' limit 1),'Serhii', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Sergey' and typ<>'=' limit 1),'Serhiy', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Sergey' and typ<>'=' limit 1),'Siarhei', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Sergey' and typ<>'=' limit 1),'Siarhej', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Sergey' and typ<>'=' limit 1),'Siarhey', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Snezhana' and typ<>'=' limit 1),'Sniazhana', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Stanislav' and typ<>'=' limit 1),'Stanislau', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Svetlana' and typ<>'=' limit 1),'Sviatlana', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Svetlana' and typ<>'=' limit 1),'Svitlana', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Tatyana' and typ<>'=' limit 1),'Tatsiana', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Tatyana' and typ<>'=' limit 1),'Tatsyana', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Tatyana' and typ<>'=' limit 1),'Tetiana', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Tatyana' and typ<>'=' limit 1),'Tetjana', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Tatyana' and typ<>'=' limit 1),'Tetyana', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Vadim' and typ<>'=' limit 1),'Vadym', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Vadim' and typ<>'=' limit 1),'Vadzim', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Valentin' and typ<>'=' limit 1),'Valentyn', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Valentina' and typ<>'=' limit 1),'Valentyna', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Valentina' and typ<>'=' limit 1),'Valiantsina', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Valeriy' and typ<>'=' limit 1),'Valerii', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Valeriya' and typ<>'=' limit 1),'Valeryia', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Vasil' and typ<>'=' limit 1),'Vasyl', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Vera' and typ<>'=' limit 1),'Vira', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Veronika' and typ<>'=' limit 1),'Veranika', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Viacheslav' and typ<>'=' limit 1),'Viachaslau', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Viacheslav' and typ<>'=' limit 1),'Viacheslau', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Viktor' and typ<>'=' limit 1),'Viktar', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Viktoriya' and typ<>'=' limit 1),'Viktoryia', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Vladimir' and typ<>'=' limit 1),'Uladzimir', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Vladimir' and typ<>'=' limit 1),'Uladzmir', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Vladimir' and typ<>'=' limit 1),'Vladymyr', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Vladimir' and typ<>'=' limit 1),'Volodimir', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Vladimir' and typ<>'=' limit 1),'Volodymyr', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Vladislav' and typ<>'=' limit 1),'Uladzislau', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Vladislav' and typ<>'=' limit 1),'Vladyslav', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Yaroslav' and typ<>'=' limit 1),'Yaraslau', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Yevgenia' and typ<>'=' limit 1),'Yauhenia', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Yevgeniy' and typ<>'=' limit 1),'Jauhen', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Yevgeniy' and typ<>'=' limit 1),'Yauhen', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Yevgeniy' and typ<>'=' limit 1),'Yauheni', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Yevgeniya' and typ<>'=' limit 1),'Yauheniya', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Yuliya' and typ<>'=' limit 1),'Yuliia', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Yuri' and typ<>'=' limit 1),'Juryj', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Yuri' and typ<>'=' limit 1),'Yurii', now(), now());
insert into Firstnames_Russia (fn_id, firstname, created_at, updated_at) values ( (select fn_id from Firstnames where firstname='Yuri' and typ<>'=' limit 1),'Yurij', now(), now());

/**
 * Insert countries and the country weight for phonetic rules
 */
delete from Countries;
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('UK', 'Großbritannien', 60, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('IE', 'Irland', 4, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('US', 'Vereinigte Staaten', 150, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('IT', 'Italien', 60, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('MT', 'Malta', 1, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('PT', 'Portugal', 10, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('ES', 'Spanien', 40, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('FR', 'Frankreich', 60, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('BE', 'Belgien', 10, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('LU', 'Luxemburg', 1, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('NL', 'Niederlande', 14, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('DE', 'Deutschland', 80, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('AT', 'Österreich', 8, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('CH', 'Schweiz', 7, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('IS', 'Island', 1, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('DK', 'Dänemark', 5, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('NO', 'Norwegen', 4, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('SE', 'Schweden', 8, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('FI', 'Finnland', 5, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('EE', 'Estland', 2, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('LV', 'Lettland', 2, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('LT', 'Litauen', 3, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('PL', 'Polen', 35, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('CZ', 'Tschechische Republik', 8, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('SK', 'Slovakei', 7, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('HU', 'Ungarn', 11, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('RO', 'Rumänien', 22, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('BG', 'Bulgarien', 9, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('BA', 'Bosnien Herzegowina', 4, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('HR', 'Kroatien', 5, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('XK', 'Kosovo', 1, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('MK', 'Mazedonien', 2, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('ME', 'Montenegro', 1, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('XS', 'Serbien', 9, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('SI', 'Slovenien', 2, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('AL', 'Albanien', 3, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('GR', 'Griechenland', 10, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('RU', 'Russland', 100, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('BU', 'Belarus', 10, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('MD', 'Moldavien', 4, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('UA', 'Ukraine', 45, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('AM', 'Armenien', 3, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('AZ', 'Aserbaidschan', 4, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('GE', 'Georgien', 5, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('KZ', 'Kasachstan', 15, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('TR', 'Türkei', 55, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('AE', 'Vereinigte Arabische Emirate', 80, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('IL', 'Israel', 4, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('CN', 'China', 300, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('IN', 'Indien', 250, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('JP', 'Japan', 35, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('KR', 'Republik Korea', 12, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('VN', 'Vietnam', 17, now(), now() );
insert into Countries (country_indicator, country, country_weight, created_at, updated_at) values ('XX', 'andere Länder', 1, now(), now() );

/**
 * Insert phonetic rules
 */
delete from Phonetic_Rules;
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('IJ',  'I',      10,  1, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('IJ',  'J',      30,  1, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('IY',  'I',      10,  1, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('IY',  'Y',      30,  1, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('I',   'J',      30,  1, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('I',   'Y',      30,  1, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('J',   'Y',      20,  1, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('IE',  'I',       5,  1, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('IE',  '',      120,  1, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('EU',  'OI',     10,  2, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('EU',  'OY',     10,  2, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('OI',  'OY',      5,  2, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('OU',  'U',       5,  2, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('AH',  'A',       5,  3, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('H',   '',       50,  3, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('Å',   'AA',      0,  3, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('Ä',   'AE',      0,  3, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('Ä',   'A',      40,  3, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('AE',  'A',      60,  3, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('Ä',   'E',      20,  4, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('Æ',   'E',      20,  4, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('A',   'ER',     70,  4, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('AE',  'E',      20,  4, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('AE',  '',      110,  4, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('AI',  'AY',      5,  4, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('AI',  'EI',      5,  4, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('AI',  'EY',     10,  4, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('AY',  'EI',     10,  4, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('AY',  'EY',      5,  4, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('EI',  'EY',      5,  4, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('Å',   'O',      70,  5, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('Ö',   'OE',      0,  5, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('Ö',   'O',      40,  5, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('Ø',   'Ö',       0,  5, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('Ø',   'OE',     10,  5, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('Ø',   'O',      30,  5, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('Œ',   'Ö',       5,  5, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('Œ',   'OE',      0,  5, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('OE',  'O',      60,  5, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('OE',  '',      110,  5, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('CHS', 'X',     100,  6, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('CKS', 'X',      30,  6, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('CK',  'K',       5,  6, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('C',   'K',      30,  6, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('CHS', '',      200,  6, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('CH',  '',      130,  6, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('CKS', '',      200,  6, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('CK',  '',      110,  6, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('DT',  'T',       5,  7, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('D',   'T',      30,  7, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('TH',  'T',       5,  7, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('DT',  '',      110,  7, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('KS',  'X',       5,  8, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('GS',  'X',      10,  8, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('G',   'K',      50,  8, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('QU',  'KW',     10,  8, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('Q',   'K',      10,  8, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('NCH', 'NSCH',   10,  9, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('NCH', 'NSH',    10,  9, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('NTX', 'NCH',    20,  9, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('NTX', 'NSCH',   20,  9, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('NTX', 'NSH',    20,  9, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('NG',  'NK',     20,  9, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('ß',   'SS',      0, 10, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('ß',   'S',       5, 10, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('SCH', 'SH',      5, 10, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('SCH', 'SZ',     20, 10, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('SCH', 'S',     100, 10, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('SCH', '',      200, 10, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('TZ',  'Z',       5, 11, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('TIA', 'ZIA',    20, 11, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('Z',   'C',      40, 11, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('Z',   'S',      50, 11, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('M',   'N',      70, 12, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('N',   'U',      70, 12, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('PH',  'F',       5, 13, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('PF',  'F',       5, 13, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('B',   'P',      40, 13, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('F',   'V',      20, 14, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('W',   'V',      20, 14, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('Ü',   'UE',      0, 15, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('Ü',   'U',      40, 15, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('Ü',   'Y',      30, 15, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('UE',  'U',      60, 15, now(), now() );
insert into Phonetic_Rules (syllable, phonetic, difference, hash_group, created_at, updated_at) values ('UE',  '',      110, 15, now(), now() );
